//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace B24.Sales3.UI {
    
    
    public partial class GeneralReport {
        
        /// <summary>
        /// AccessDeniedErrorLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label AccessDeniedErrorLabel;
        
        /// <summary>
        /// ManageAccountUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::B24.Sales3.UserControl.ManageAccount ManageAccountUserControl;
        
        /// <summary>
        /// AdvanceReportUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel AdvanceReportUpdatePanel;
        
        /// <summary>
        /// AdvanceReportUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::B24.Sales3.UserControl.AdvanceReport AdvanceReportUserControl;
    }
}
