//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough seats for all the users specified. Remove some users and/or increase the seat count..
        /// </summary>
        internal static string AccountUpdateSeatNotEnough {
            get {
                return ResourceManager.GetString("AccountUpdateSeatNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not unassign the user from subscription..
        /// </summary>
        internal static string AccountUpdateUnAssignUserError {
            get {
                return ResourceManager.GetString("AccountUpdateUnAssignUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name changed.
        /// </summary>
        internal static string ApplicationChanged {
            get {
                return ResourceManager.GetString("ApplicationChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name not found in the list.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to bind values.
        /// </summary>
        internal static string BindValues {
            get {
                return ResourceManager.GetString("BindValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection added successfully.
        /// </summary>
        internal static string CollectionAdded {
            get {
                return ResourceManager.GetString("CollectionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection deleted.
        /// </summary>
        internal static string CollectionDeleted {
            get {
                return ResourceManager.GetString("CollectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add a collection .
        /// </summary>
        internal static string CollectionNotAdded {
            get {
                return ResourceManager.GetString("CollectionNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete collection.
        /// </summary>
        internal static string CollectionNotDeleted {
            get {
                return ResourceManager.GetString("CollectionNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update collection.
        /// </summary>
        internal static string CollectionNotUpdated {
            get {
                return ResourceManager.GetString("CollectionNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection updated successfully.
        /// </summary>
        internal static string CollectionUpdated {
            get {
                return ResourceManager.GetString("CollectionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name not provided.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostCenter added successfully.
        /// </summary>
        internal static string CostCenterAdded {
            get {
                return ResourceManager.GetString("CostCenterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Deleted.
        /// </summary>
        internal static string CostCenterDeleted {
            get {
                return ResourceManager.GetString("CostCenterDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center Updated Successfully.
        /// </summary>
        internal static string CostCenterUpdated {
            get {
                return ResourceManager.GetString("CostCenterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should be greater than start date.
        /// </summary>
        internal static string DateComparison {
            get {
                return ResourceManager.GetString("DateComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the collection from subscription..
        /// </summary>
        internal static string DeleteCollectionFail {
            get {
                return ResourceManager.GetString("DeleteCollectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name not provided.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter domain to add or select a domain to remove..
        /// </summary>
        internal static string DomainNotSelected {
            get {
                return ResourceManager.GetString("DomainNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update email domain.
        /// </summary>
        internal static string DomainNotUpdated {
            get {
                return ResourceManager.GetString("DomainNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated email domain.
        /// </summary>
        internal static string DomainUpdated {
            get {
                return ResourceManager.GetString("DomainUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send email.
        /// </summary>
        internal static string EmailSendingFail {
            get {
                return ResourceManager.GetString("EmailSendingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the Email Settings.
        /// </summary>
        internal static string EmailSettingsFail {
            get {
                return ResourceManager.GetString("EmailSettingsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load Email Settings.
        /// </summary>
        internal static string EmailSettingsLoadFail {
            get {
                return ResourceManager.GetString("EmailSettingsLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings Updated Successful.
        /// </summary>
        internal static string EmailSettingsSuccess {
            get {
                return ResourceManager.GetString("EmailSettingsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date not provided.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date not valid.
        /// </summary>
        internal static string EndDateValid {
            get {
                return ResourceManager.GetString("EndDateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while  loading the page.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on  Adding Extend Attribute.
        /// </summary>
        internal static string ErrorAddingExtendAttribute {
            get {
                return ResourceManager.GetString("ErrorAddingExtendAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding rule.
        /// </summary>
        internal static string ErrorAddingRule {
            get {
                return ResourceManager.GetString("ErrorAddingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Deleting Cost Center.
        /// </summary>
        internal static string ErrorDeletingCostCenter {
            get {
                return ResourceManager.GetString("ErrorDeletingCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting rule.
        /// </summary>
        internal static string ErrorDeletingRule {
            get {
                return ResourceManager.GetString("ErrorDeletingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting rules for subscription.
        /// </summary>
        internal static string ErrorGettingRules {
            get {
                return ResourceManager.GetString("ErrorGettingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the control.
        /// </summary>
        internal static string ErrorLoadControl {
            get {
                return ResourceManager.GetString("ErrorLoadControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales3 error.
        /// </summary>
        internal static string ErrorSales3 {
            get {
                return ResourceManager.GetString("ErrorSales3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on updating Cost Center.
        /// </summary>
        internal static string ErrorUpdatingCostCenter {
            get {
                return ResourceManager.GetString("ErrorUpdatingCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating rule.
        /// </summary>
        internal static string ErrorUpdatingRule {
            get {
                return ResourceManager.GetString("ErrorUpdatingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Attribute Added Successfully.
        /// </summary>
        internal static string ExtendAttributeAdded {
            get {
                return ResourceManager.GetString("ExtendAttributeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the Extend Trial.
        /// </summary>
        internal static string ExtendTrialFail {
            get {
                return ResourceManager.GetString("ExtendTrialFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application doesn&apos;t support tickets.
        /// </summary>
        internal static string ImpersonateAppError {
            get {
                return ResourceManager.GetString("ImpersonateAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonation failed.
        /// </summary>
        internal static string ImpersonateFail {
            get {
                return ResourceManager.GetString("ImpersonateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t impersonate this user. The user might be a super user or sales manager or general admin..
        /// </summary>
        internal static string ImpersonatePermission {
            get {
                return ResourceManager.GetString("ImpersonatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit auth rules for a non-library subscription.
        /// </summary>
        internal static string LibraryRulesAuthError {
            get {
                return ResourceManager.GetString("LibraryRulesAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create library trial subscription.
        /// </summary>
        internal static string LibraryTrialSubscriptionNotCreated {
            get {
                return ResourceManager.GetString("LibraryTrialSubscriptionNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null refrence exception.
        /// </summary>
        internal static string NullReference {
            get {
                return ResourceManager.GetString("NullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not upload the logo.
        /// </summary>
        internal static string PartnerLogoFail {
            get {
                return ResourceManager.GetString("PartnerLogoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load Partner Logo.
        /// </summary>
        internal static string PartnerLogoGetFail {
            get {
                return ResourceManager.GetString("PartnerLogoGetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner logo image uploaded successfully.
        /// </summary>
        internal static string PartnerLogoSuccess {
            get {
                return ResourceManager.GetString("PartnerLogoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner name not provided.
        /// </summary>
        internal static string PartnerName {
            get {
                return ResourceManager.GetString("PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update password.
        /// </summary>
        internal static string PasswordFail {
            get {
                return ResourceManager.GetString("PasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 3 and 63 characters.
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password must match with the new password.
        /// </summary>
        internal static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated.
        /// </summary>
        internal static string PasswordUpdate {
            get {
                return ResourceManager.GetString("PasswordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path name not provided.
        /// </summary>
        internal static string PathName {
            get {
                return ResourceManager.GetString("PathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check &quot;confirm&quot; and resubmit..
        /// </summary>
        internal static string RemoveRestoreConfirm {
            get {
                return ResourceManager.GetString("RemoveRestoreConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove or restore user.
        /// </summary>
        internal static string RemoveRestoreUserFail {
            get {
                return ResourceManager.GetString("RemoveRestoreUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule added.
        /// </summary>
        internal static string RuleAdded {
            get {
                return ResourceManager.GetString("RuleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule deleted.
        /// </summary>
        internal static string RuleDeleted {
            get {
                return ResourceManager.GetString("RuleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule updated.
        /// </summary>
        internal static string RuleUpdated {
            get {
                return ResourceManager.GetString("RuleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select categories.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image file only.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the logo image to upload.
        /// </summary>
        internal static string SelectLogo {
            get {
                return ResourceManager.GetString("SelectLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update self registration.
        /// </summary>
        internal static string SelfRegistraionUpdateFailed {
            get {
                return ResourceManager.GetString("SelfRegistraionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You cannot enable self reg without defining some domain rules..
        /// </summary>
        internal static string SelfRegistrationCannotEnable {
            get {
                return ResourceManager.GetString("SelfRegistrationCannotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self registration updated.
        /// </summary>
        internal static string SelfRegistrationChanged {
            get {
                return ResourceManager.GetString("SelfRegistrationChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Self Registration Instructions Failed.
        /// </summary>
        internal static string SelfRegistrationFailed {
            get {
                return ResourceManager.GetString("SelfRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Retrieve Self Registration Instructions.
        /// </summary>
        internal static string SelfRegistrationFetchFailed {
            get {
                return ResourceManager.GetString("SelfRegistrationFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Self Registration Instructions.
        /// </summary>
        internal static string SelfRegistrationUpdated {
            get {
                return ResourceManager.GetString("SelfRegistrationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter sharedsecret..
        /// </summary>
        internal static string SharedSecretNotSelected {
            get {
                return ResourceManager.GetString("SharedSecretNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared secret code not updated.
        /// </summary>
        internal static string SharedSecretNotUpdated {
            get {
                return ResourceManager.GetString("SharedSecretNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated shared secret.
        /// </summary>
        internal static string SharedSecretUpdated {
            get {
                return ResourceManager.GetString("SharedSecretUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the single sign on subscription.
        /// </summary>
        internal static string SignOnFail {
            get {
                return ResourceManager.GetString("SignOnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single sign on subscription updated successfully.
        /// </summary>
        internal static string SignOnSuccess {
            get {
                return ResourceManager.GetString("SignOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date not provided.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date not valid.
        /// </summary>
        internal static string StartsDateValid {
            get {
                return ResourceManager.GetString("StartsDateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update subscription.
        /// </summary>
        internal static string SubFail {
            get {
                return ResourceManager.GetString("SubFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the subscription flag.
        /// </summary>
        internal static string SubFlagFail {
            get {
                return ResourceManager.GetString("SubFlagFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription flag updated successfully.
        /// </summary>
        internal static string SubFlagSuccess {
            get {
                return ResourceManager.GetString("SubFlagSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription alert created.
        /// </summary>
        internal static string SubscriptionAlertCreated {
            get {
                return ResourceManager.GetString("SubscriptionAlertCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create new alert.
        /// </summary>
        internal static string SubscriptionAlertNotCreated {
            get {
                return ResourceManager.GetString("SubscriptionAlertNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the subscription alert .
        /// </summary>
        internal static string SubscriptionAlertNotUpdated {
            get {
                return ResourceManager.GetString("SubscriptionAlertNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription alert updated.
        /// </summary>
        internal static string SubscriptionAlertUpdated {
            get {
                return ResourceManager.GetString("SubscriptionAlertUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load subscription flags.
        /// </summary>
        internal static string SubscriptionFlagNotLoaded {
            get {
                return ResourceManager.GetString("SubscriptionFlagNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load subscription.
        /// </summary>
        internal static string SubscriptonNotLoaded {
            get {
                return ResourceManager.GetString("SubscriptonNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription updated successfully.
        /// </summary>
        internal static string SubSuccess {
            get {
                return ResourceManager.GetString("SubSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription type not found in the list.
        /// </summary>
        internal static string SubType {
            get {
                return ResourceManager.GetString("SubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder does not exists.
        /// </summary>
        internal static string TargetFolder {
            get {
                return ResourceManager.GetString("TargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Load the Update Account Deatils.
        /// </summary>
        internal static string UpdateAccountLoadError {
            get {
                return ResourceManager.GetString("UpdateAccountLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added to subscription administrator.
        /// </summary>
        internal static string UserAdministratorAdded {
            get {
                return ResourceManager.GetString("UserAdministratorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm administrator reassignment..
        /// </summary>
        internal static string UserAdministratorConfirm {
            get {
                return ResourceManager.GetString("UserAdministratorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User removed from subscription administrator.
        /// </summary>
        internal static string UserAdministratorRemoved {
            get {
                return ResourceManager.GetString("UserAdministratorRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update user details.
        /// </summary>
        internal static string UserDetailFail {
            get {
                return ResourceManager.GetString("UserDetailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details updated.
        /// </summary>
        internal static string UserDetailSuccess {
            get {
                return ResourceManager.GetString("UserDetailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update entitlement.
        /// </summary>
        internal static string UserEntilementFailed {
            get {
                return ResourceManager.GetString("UserEntilementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User entitlements updated.
        /// </summary>
        internal static string UserEntitlementUpdated {
            get {
                return ResourceManager.GetString("UserEntitlementUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading user details.
        /// </summary>
        internal static string UserLoadError {
            get {
                return ResourceManager.GetString("UserLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added users.
        /// </summary>
        internal static string UsersAdded {
            get {
                return ResourceManager.GetString("UsersAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add one or more users.
        /// </summary>
        internal static string UsersNotAdded {
            get {
                return ResourceManager.GetString("UsersNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated.
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t modify email id for this subscription.
        /// </summary>
        internal static string WelcomeMessageCannotModify {
            get {
                return ResourceManager.GetString("WelcomeMessageCannotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification is failed.
        /// </summary>
        internal static string WelcomeMessageFailed {
            get {
                return ResourceManager.GetString("WelcomeMessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome message sender is successfully modified.
        /// </summary>
        internal static string WelcomeMessageUpdated {
            get {
                return ResourceManager.GetString("WelcomeMessageUpdated", resourceCulture);
            }
        }
    }
}
